import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, "..");

function parseEnv(text) {
  const vars = new Map();
  for (const line of text.split(/\r?\n/)) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith("#")) continue;
    const eq = trimmed.indexOf("=");
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    vars.set(key, value);
  }
  return vars;
}

function loadExample(relativePath) {
  const filePath = path.join(root, relativePath);
  if (!fs.existsSync(filePath)) return new Map();
  return parseEnv(fs.readFileSync(filePath, "utf8"));
}

function mergeEnv(...maps) {
  const merged = new Map();
  for (const map of maps) {
    for (const [key, value] of map) merged.set(key, value);
  }
  return merged;
}

function serializeEnv(header, keys, vars) {
  const lines = [header, ""];
  for (const key of keys) {
    if (vars.has(key)) lines.push(`${key}=${vars.get(key)}`);
  }
  lines.push("");
  return lines.join("\n");
}

function writeEnv(relativePath, content) {
  const filePath = path.join(root, relativePath);
  fs.writeFileSync(filePath, content, "utf8");
  console.log(`Wrote ${relativePath}`);
}

const rootEnvPath = path.join(root, ".env");
const rootExample = loadExample(".env.example");
const rootLive = fs.existsSync(rootEnvPath) ? parseEnv(fs.readFileSync(rootEnvPath, "utf8")) : new Map();
const shared = mergeEnv(rootExample, rootLive);

const SHARED_KEYS = [
  "DATABASE_URL",
  "ENGINE_ADMIN_KEY",
  "ENGINE_ACCESS_KEYS",
  "WALLET_ENCRYPTION_KEY",
  "SESSION_JWT_SECRET",
  "LOG_LEVEL",
  "DEFAULT_API_KEY_RATE_LIMIT_PER_MINUTE",
  "GLOBAL_IP_RATE_LIMIT_PER_MINUTE",
  "CDP_API_KEY_ID",
  "CDP_API_KEY_SECRET",
  "WEBHOOK_URL",
  "WEBHOOK_SECRET",
  "DEPLOYER_PRIVATE_KEY",
  "ENGINE_URL",
  "ENGINE_API_KEY",
  "VITE_ENGINE_URL",
  "VITE_INSIGHT_URL",
  "VITE_DEFAULT_API_KEY",
];

for (const [key, value] of shared) {
  if (key.startsWith("CHAIN_")) SHARED_KEYS.push(key);
}

const chainKeys = [...shared.keys()].filter((k) => k.startsWith("CHAIN_"));
const allSharedKeys = [...new Set([...SHARED_KEYS, ...chainKeys])];

const engineExample = loadExample("apps/engine/.env.example");
const insightExample = loadExample("apps/insight/.env.example");
const dashboardExample = loadExample("apps/dashboard/.env.example");
const contractsExample = loadExample("packages/contracts/.env.example");

const engineVars = mergeEnv(shared, engineExample);
const insightVars = mergeEnv(shared, insightExample);
const dashboardVars = mergeEnv(shared, dashboardExample);
const contractsVars = mergeEnv(shared, contractsExample);

writeEnv(
  "apps/engine/.env",
  serializeEnv(
    "# Generated by npm run env:sync — edit root .env and re-run.",
    [...allSharedKeys, ...engineExample.keys()],
    engineVars
  )
);

writeEnv(
  "apps/insight/.env",
  serializeEnv(
    "# Generated by npm run env:sync — edit root .env and re-run.",
    [...allSharedKeys, ...insightExample.keys()],
    insightVars
  )
);

writeEnv(
  "apps/dashboard/.env",
  serializeEnv(
    "# Generated by npm run env:sync — edit root .env and re-run.",
    [...dashboardExample.keys()],
    dashboardVars
  )
);

writeEnv(
  "packages/contracts/.env",
  serializeEnv(
    "# Generated by npm run env:sync — edit root .env and re-run.",
    [...contractsExample.keys(), ...chainKeys, "DEPLOYER_PRIVATE_KEY", "ENGINE_URL", "ENGINE_API_KEY"],
    contractsVars
  )
);

console.log("Done. Service .env files updated from root .env (or .env.example defaults).");
